-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 15:03:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ds1_web_semestralka2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ds1_web_semestralka2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ds1_web_semestralka2` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `ds1_web_semestralka2` ;

-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`ds1_obyvatele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`ds1_obyvatele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NULL,
  `prijmeni` VARCHAR(45) NULL,
  `rodne_prijmeni` VARCHAR(45) NULL,
  `datum_narozeni` DATE NULL,
  `tituly_pred` VARCHAR(30) NULL,
  `tituly_za` VARCHAR(30) NULL,
  `rodne_cislo` VARCHAR(20) NULL,
  `misto_narozeni` VARCHAR(100) NULL,
  `pojistovna_zkratka` VARCHAR(45) NULL,
  `cislo_pojistence` INT NULL,
  `adresa_ulice` VARCHAR(100) NULL,
  `adresa_cp` VARCHAR(45) NULL,
  `adresa_mesto` VARCHAR(100) NULL,
  `op` INT NULL,
  `op_platnost_do` DATE NULL,
  `stav` TINYINT NULL DEFAULT 1 COMMENT '1 ok aktivni, 2 neaktivni\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`typ_vykonu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`typ_vykonu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NULL,
  `popis` TEXT NULL,
  `role id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`sluzba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`sluzba` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `obyvatel_id` INT NOT NULL,
  `typ_vykonu_id` INT NOT NULL,
  `datum_od` DATE NULL,
  `datum_do` DATE NULL,
  `poznamka` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sluzba_typ_vykonu_idx` (`typ_vykonu_id` ASC),
  INDEX `fk_sluzba_obyvatele1_idx` (`obyvatel_id` ASC),
  CONSTRAINT `fk_sluzba_typ_vykonu`
    FOREIGN KEY (`typ_vykonu_id`)
    REFERENCES `ds1_web_semestralka2`.`typ_vykonu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sluzba_obyvatele1`
    FOREIGN KEY (`obyvatel_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_obyvatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`plan_vykonu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`plan_vykonu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sluzba_id` INT NOT NULL,
  `typ_planu` INT NULL DEFAULT 1 COMMENT '1=tydenni, 2=mesicni, 3=jednorazovy a pak se pouzije presny sloupec datum = presny datum bez casu - lze takto konstantami nebo je treba vest ciselnik? Konstanty jsou dle meho nazoru lepsi a jednodussi.',
  `cas_od` TIME NULL,
  `cas_do` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plan_vykonu_sluzba1_idx` (`sluzba_id` ASC),
  CONSTRAINT `fk_plan_vykonu_sluzba1`
    FOREIGN KEY (`sluzba_id`)
    REFERENCES `ds1_web_semestralka2`.`sluzba` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`ds1_uzivatele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`ds1_uzivatele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password_bcrypt` VARCHAR(255) NOT NULL,
  `jmeno` VARCHAR(45) NULL,
  `prijmeni` VARCHAR(45) NULL,
  `telefon` VARCHAR(20) NULL,
  `email` VARCHAR(150) NULL,
  `pravo` INT NULL,
  `datum_vytvoreni` DATETIME NULL,
  `smazano` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`zaznam_vykonu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`zaznam_vykonu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plan_vykonu_id` INT NOT NULL,
  `uzivatel_id` INT NOT NULL,
  `cas_zacatek` TIME NULL,
  `cas_konec` TIME NULL,
  `poznamka` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zaznam_vykonu_plan_vykonu1_idx` (`plan_vykonu_id` ASC),
  INDEX `fk_zaznam_vykonu_uzivatele1_idx` (`uzivatel_id` ASC),
  CONSTRAINT `fk_zaznam_vykonu_plan_vykonu1`
    FOREIGN KEY (`plan_vykonu_id`)
    REFERENCES `ds1_web_semestralka2`.`plan_vykonu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zaznam_vykonu_uzivatele1`
    FOREIGN KEY (`uzivatel_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_uzivatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`dokumentace_druh_zapisu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`dokumentace_druh_zapisu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `barva_hex` VARCHAR(25) NOT NULL,
  `tucne` TINYINT NULL DEFAULT 0,
  `kurziva` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`dokumentace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`dokumentace` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_id` INT NOT NULL,
  `obyvatel_id` INT NOT NULL,
  `dokumentace_typ_zapisu_id` INT NOT NULL,
  `zapis` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dokumentace_obyvatele1_idx` (`obyvatel_id` ASC),
  INDEX `fk_dokumentace_table11_idx` (`dokumentace_typ_zapisu_id` ASC),
  INDEX `fk_dokumentace_uzivatele1_idx` (`uzivatel_id` ASC),
  CONSTRAINT `fk_dokumentace_obyvatele1`
    FOREIGN KEY (`obyvatel_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_obyvatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dokumentace_table11`
    FOREIGN KEY (`dokumentace_typ_zapisu_id`)
    REFERENCES `ds1_web_semestralka2`.`dokumentace_druh_zapisu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dokumentace_uzivatele1`
    FOREIGN KEY (`uzivatel_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_uzivatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`defekty_obyvatele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`defekty_obyvatele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `obyvatel_id` INT NOT NULL,
  `nazev` VARCHAR(255) NULL,
  `popis` TEXT NULL,
  `datum_zacatek` DATETIME NULL,
  `datum_konec` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_defekty_obyvatele_obyvatele1_idx` (`obyvatel_id` ASC),
  CONSTRAINT `fk_defekty_obyvatele_obyvatele1`
    FOREIGN KEY (`obyvatel_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_obyvatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`defekty_obyvatele_prubeh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`defekty_obyvatele_prubeh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `defekt_obyvatele_id` INT NOT NULL,
  `popis` TEXT NULL,
  `stav` INT NULL COMMENT 'stav - konstanty, 0 = stejny, 1 = zlepseni, 2 = zhorseni',
  `datum_vytvoreni` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_defekty_obyvatele_prubeh_defekty_obyvatele1_idx` (`defekt_obyvatele_id` ASC),
  CONSTRAINT `fk_defekty_obyvatele_prubeh_defekty_obyvatele1`
    FOREIGN KEY (`defekt_obyvatele_id`)
    REFERENCES `ds1_web_semestralka2`.`defekty_obyvatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`ds1_skupiny_pokoju`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`ds1_skupiny_pokoju` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NULL,
  `poznamka` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`ds1_pokoje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`ds1_pokoje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `skupina_pokoju_id` INT NOT NULL,
  `nazev` VARCHAR(45) NULL,
  `poschodi` INT NULL,
  `socialni_zarizeni` INT NULL,
  `popis` TEXT NULL,
  `kapacita_osob` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_ds1_pokoje2_ds1_skupina_pokoju1_idx` (`skupina_pokoju_id` ASC),
  CONSTRAINT `fk_ds1_pokoje2_ds1_skupina_pokoju1`
    FOREIGN KEY (`skupina_pokoju_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_skupiny_pokoju` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`ds1_obyvatele_na_pokojich`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`ds1_obyvatele_na_pokojich` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `obyvatel_id` INT NOT NULL,
  `pokoj_id` INT NOT NULL,
  `datum_od` DATETIME NULL,
  `datum_do` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_obyvatele_na_pokojich_obyvatele1_idx` (`obyvatel_id` ASC),
  INDEX `fk_ds1_obyvatele_na_pokojich_ds1_pokoje21_idx` (`pokoj_id` ASC),
  CONSTRAINT `fk_obyvatele_na_pokojich_obyvatele1`
    FOREIGN KEY (`obyvatel_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_obyvatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ds1_obyvatele_na_pokojich_ds1_pokoje21`
    FOREIGN KEY (`pokoj_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_pokoje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`uzivatelske_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`uzivatelske_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `popis` TEXT NULL,
  `datum_vytvoreni` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`pokoje_individualni_cena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`pokoje_individualni_cena` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pokoj_id` INT NOT NULL,
  `nazev` VARCHAR(100) NULL,
  `poznamka` TEXT NULL,
  `platnost_od` DATETIME NULL,
  `platnost_do` DATETIME NULL,
  `cena_osoba_s_dph` FLOAT NULL,
  `ds1_pokoje2_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pokoje_individualni_cena_ds1_pokoje21_idx` (`ds1_pokoje2_id` ASC),
  CONSTRAINT `fk_pokoje_individualni_cena_ds1_pokoje21`
    FOREIGN KEY (`ds1_pokoje2_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_pokoje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`skupiny_pokoju_ceny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`skupiny_pokoju_ceny` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `skupina_pokoju_id` INT NOT NULL,
  `datum_od` DATETIME NULL,
  `datum_do` DATETIME NULL,
  `cena_osoba_s_dph` FLOAT NULL,
  `poznamka` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skupiny_pokoju_ceny_skupina_pokoju1_idx` (`skupina_pokoju_id` ASC),
  CONSTRAINT `fk_skupiny_pokoju_ceny_skupina_pokoju1`
    FOREIGN KEY (`skupina_pokoju_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_skupiny_pokoju` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`uzivatele_prideleni_roli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`uzivatele_prideleni_roli` (
  `uzivatele_id` INT NOT NULL,
  `uzivatele_role_id` INT NOT NULL,
  `datum_vytvoreni` DATETIME NULL,
  PRIMARY KEY (`uzivatele_id`, `uzivatele_role_id`),
  INDEX `fk_uzivatele_has_uzivatele_role_uzivatele_role1_idx` (`uzivatele_role_id` ASC),
  INDEX `fk_uzivatele_has_uzivatele_role_uzivatele1_idx` (`uzivatele_id` ASC),
  CONSTRAINT `fk_uzivatele_has_uzivatele_role_uzivatele1`
    FOREIGN KEY (`uzivatele_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_uzivatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatele_has_uzivatele_role_uzivatele_role1`
    FOREIGN KEY (`uzivatele_role_id`)
    REFERENCES `ds1_web_semestralka2`.`uzivatelske_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`zaznam_vykonu_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`zaznam_vykonu_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zaznam_vykonu_id` INT NOT NULL,
  `uzivatel_id` INT NOT NULL,
  `nazev` VARCHAR(100) NULL,
  `popis` TEXT NULL,
  `lecivo` VARCHAR(100) NULL,
  `mnozstvi_ml` INT NULL,
  `mnozsvi_mg` INT NULL,
  `mnozstvi_text` VARCHAR(100) NULL,
  `datum_vytvoreni` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zaznam_vykonu_detail_zaznam_vykonu1_idx` (`zaznam_vykonu_id` ASC),
  INDEX `fk_zaznam_vykonu_detail_uzivatele1_idx` (`uzivatel_id` ASC),
  CONSTRAINT `fk_zaznam_vykonu_detail_zaznam_vykonu1`
    FOREIGN KEY (`zaznam_vykonu_id`)
    REFERENCES `ds1_web_semestralka2`.`zaznam_vykonu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zaznam_vykonu_detail_uzivatele1`
    FOREIGN KEY (`uzivatel_id`)
    REFERENCES `ds1_web_semestralka2`.`ds1_uzivatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds1_web_semestralka2`.`druh_zapisu_uzivatelske_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds1_web_semestralka2`.`druh_zapisu_uzivatelske_role` (
  `dokumentace_druh_zapisu_id` INT NOT NULL,
  `uzivatelske_role_id` INT NOT NULL,
  PRIMARY KEY (`dokumentace_druh_zapisu_id`, `uzivatelske_role_id`),
  INDEX `fk_dokumentace_druh_zapisu_has_uzivatelske_role_uzivatelske_idx` (`uzivatelske_role_id` ASC),
  INDEX `fk_dokumentace_druh_zapisu_has_uzivatelske_role_dokumentace_idx` (`dokumentace_druh_zapisu_id` ASC),
  CONSTRAINT `fk_dokumentace_druh_zapisu_has_uzivatelske_role_dokumentace_d1`
    FOREIGN KEY (`dokumentace_druh_zapisu_id`)
    REFERENCES `ds1_web_semestralka2`.`dokumentace_druh_zapisu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dokumentace_druh_zapisu_has_uzivatelske_role_uzivatelske_r1`
    FOREIGN KEY (`uzivatelske_role_id`)
    REFERENCES `ds1_web_semestralka2`.`uzivatelske_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
